//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ui.Tests.Steps.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CopyrightTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CopyrightTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ui.Tests.Steps.TestData.CopyrightTestData", typeof(CopyrightTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity Risk Underwriters, LLC
        ///20 Burton Hills Blvd Ste 350 Nashville, TN 37215 (map).
        /// </summary>
        internal static string CorporateOfficeAddress {
            get {
                return ResourceManager.GetString("CorporateOfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://velocityrisk.com/disclaimer/.
        /// </summary>
        internal static string DisclaimerUrl {
            get {
                return ResourceManager.GetString("DisclaimerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/velocityriskunderwriters/.
        /// </summary>
        internal static string FacebookHref {
            get {
                return ResourceManager.GetString("FacebookHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://web.facebook.com/velocityriskunderwriters/?_rdc=1&amp;_rdr.
        /// </summary>
        internal static string FacebookUrl {
            get {
                return ResourceManager.GetString("FacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/velocityrisk/.
        /// </summary>
        internal static string InstagramHref {
            get {
                return ResourceManager.GetString("InstagramHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/velocityrisk/.
        /// </summary>
        internal static string InstagramUrl {
            get {
                return ResourceManager.GetString("InstagramUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (615) 942-0740.
        /// </summary>
        internal static string LargeCommercialPhoneNumber {
            get {
                return ResourceManager.GetString("LargeCommercialPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel:(615)942-0740.
        /// </summary>
        internal static string LargeCommercialPhoneNumberLink {
            get {
                return ResourceManager.GetString("LargeCommercialPhoneNumberLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.linkedin.com/company/velocity-risk-underwriters-llc/.
        /// </summary>
        internal static string LinkedInHref {
            get {
                return ResourceManager.GetString("LinkedInHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.linkedin.com/company/velocity-risk-underwriters-llc/.
        /// </summary>
        internal static string LinkedInUrl {
            get {
                return ResourceManager.GetString("LinkedInUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (844) 878-7529.
        /// </summary>
        internal static string PersonalLinesPhoneNumber {
            get {
                return ResourceManager.GetString("PersonalLinesPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel:(844)878-7529.
        /// </summary>
        internal static string PersonalLinesPhoneNumberLink {
            get {
                return ResourceManager.GetString("PersonalLinesPhoneNumberLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://velocityrisk.com/privacy-policy/.
        /// </summary>
        internal static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://velocityrisk.com/claims/.
        /// </summary>
        internal static string ReportClaimOnlineUrl {
            get {
                return ResourceManager.GetString("ReportClaimOnlineUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel:(844)878-2567.
        /// </summary>
        internal static string ReportClaimPhoneLink {
            get {
                return ResourceManager.GetString("ReportClaimPhoneLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (844) 878-2567.
        /// </summary>
        internal static string ReportClaimPhoneNumber {
            get {
                return ResourceManager.GetString("ReportClaimPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (844) 878-1267.
        /// </summary>
        internal static string SmallCommercialPhoneNumber {
            get {
                return ResourceManager.GetString("SmallCommercialPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel:(844)878-1267.
        /// </summary>
        internal static string SmallCommercialPhoneNumberLink {
            get {
                return ResourceManager.GetString("SmallCommercialPhoneNumberLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://velocityrisk.com/terms-of-use/.
        /// </summary>
        internal static string TermsOfUseUrl {
            get {
                return ResourceManager.GetString("TermsOfUseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/velocityrisk.
        /// </summary>
        internal static string TwitterHref {
            get {
                return ResourceManager.GetString("TwitterHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/velocityrisk.
        /// </summary>
        internal static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
    }
}
