//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ui.Tests.Steps.TestData.Customers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClaimsTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClaimsTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ui.Tests.Steps.TestData.Customers.ClaimsTestData", typeof(ClaimsTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New resource has tips, public education materials for Texas cities &amp; counties
        ///
        ///The Texas Department of Insurance (TDI) created an online toolkit to help city and county officials protect residents from scam artists after a storm or disaster.
        ///
        ///“It’s important to get information to storm victims fast,” said Texas Insurance Commissioner Kent Sullivan. “People want to start the repair and recovery process as quickly as possible. Good information helps consumers make good decisions.”
        ///
        ///After a major storm,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdditionalResourcesContent {
            get {
                return ResourceManager.GetString("AdditionalResourcesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Resources.
        /// </summary>
        internal static string AdditionalResourcesTitle {
            get {
                return ResourceManager.GetString("AdditionalResourcesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every claim is unique; however, all claims generally follow these three phases:
        ///
        ///1. Contact and Claims Advancement
        ///
        ///After reporting your claim, it will be assigned to one of our experienced claim professionals. This claim handler will guide you through the process and work with a team of other associated claim professionals to manage your claim promptly and accurately to conclusion. In this phase, you will be contacted by your claim professional and he/she will:
        ///
        ///Fully explain the claims process
        ///Sche [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClaimsProcessContent {
            get {
                return ResourceManager.GetString("ClaimsProcessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our claims process.
        /// </summary>
        internal static string ClaimsProcessTitle {
            get {
                return ResourceManager.GetString("ClaimsProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you’d like to quickly and conveniently report a claim, we can help:
        ///
        ///Call us 24/7 at 844­-VRU-­CLMS (844-­878-­2567),
        ///Reach out to your agent, or
        ///File a claim online using the appropriate option below:
        ///
        ///For homeowners, click here and use client access code vel6475.
        ///
        ///For small commercial, click here and use client access code vel6942 or email your claim to smallbusiness.claims@velocityrisk.com.
        ///
        ///For large commercial, click here and use client access code vel6459 or email your claim to business.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileClaimContent {
            get {
                return ResourceManager.GetString("FileClaimContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a claim.
        /// </summary>
        internal static string FileClaimTitle {
            get {
                return ResourceManager.GetString("FileClaimTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does Velocity Claims Services offer?
        ///
        ///Our Velocity Claims team is staffed with caring and helpful professionals, available 24/7 to answer your questions and help you through the claims process.
        ///
        ///Who should I contact to report a loss?
        ///
        ///You should let your insurance agent know, but to get the claims process moving quickly, call us at 1-844-VRU-CLMS (844-878-2567) or visit the File a Claim section on this page. One of our customer service professionals will ask you a few questions to get the informa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GeneralFaqsContent {
            get {
                return ResourceManager.GetString("GeneralFaqsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General FAQs.
        /// </summary>
        internal static string GeneralFaqsTitle {
            get {
                return ResourceManager.GetString("GeneralFaqsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents.
        /// </summary>
        internal static string MenuAgents {
            get {
                return ResourceManager.GetString("MenuAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://velocityrisk.com/for-agents/.
        /// </summary>
        internal static string MenuAgentsLink {
            get {
                return ResourceManager.GetString("MenuAgentsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims.
        /// </summary>
        internal static string MenuClaims {
            get {
                return ResourceManager.GetString("MenuClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://velocityrisk.com/claims/.
        /// </summary>
        internal static string MenuClaimsLink {
            get {
                return ResourceManager.GetString("MenuClaimsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homeowners.
        /// </summary>
        internal static string MenuHomeowners {
            get {
                return ResourceManager.GetString("MenuHomeowners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://velocityrisk.com/for-homeowners/.
        /// </summary>
        internal static string MenuHomeownersLink {
            get {
                return ResourceManager.GetString("MenuHomeownersLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Commercial.
        /// </summary>
        internal static string MenuLargeCommercial {
            get {
                return ResourceManager.GetString("MenuLargeCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://velocityrisk.com/for-businesses/large_business/.
        /// </summary>
        internal static string MenuLargeCommercialLink {
            get {
                return ResourceManager.GetString("MenuLargeCommercialLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a Payment.
        /// </summary>
        internal static string MenuMakePayment {
            get {
                return ResourceManager.GetString("MenuMakePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://portal.icheckgateway.com/Velocity/.
        /// </summary>
        internal static string MenuMakePaymentLink {
            get {
                return ResourceManager.GetString("MenuMakePaymentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your Policy.
        /// </summary>
        internal static string MenuManageYourPolicy {
            get {
                return ResourceManager.GetString("MenuManageYourPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://portal.velocityrisk.com/Login.aspx?ReturnUrl=%2f.
        /// </summary>
        internal static string MenuManageYourPolicyLink {
            get {
                return ResourceManager.GetString("MenuManageYourPolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes and News.
        /// </summary>
        internal static string MenuNotesAndNews {
            get {
                return ResourceManager.GetString("MenuNotesAndNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://velocityrisk.com/news-and-notes/.
        /// </summary>
        internal static string MenuNotesAndNewsLink {
            get {
                return ResourceManager.GetString("MenuNotesAndNewsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Commercial.
        /// </summary>
        internal static string MenuSmallCommercial {
            get {
                return ResourceManager.GetString("MenuSmallCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://velocityrisk.com/small_business/.
        /// </summary>
        internal static string MenuSmallCommercialLink {
            get {
                return ResourceManager.GetString("MenuSmallCommercialLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I choose who will do repairs to my property?
        ///
        ///Yes. Your Velocity claims representative will work with your choice of vendor or contractor. We may offer and explain the benefits of our Velocity Direct Repair™ program as an option to you, however, it is always your choice which vendor or contractor you use.
        ///
        ///Will repairs be done properly and workmanship guaranteed?
        ///
        ///By choosing your own contractor/vendor, you manage their work and ensure that the repairs meet your standards. We do not make any warra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PropertyClaimFaqsContent {
            get {
                return ResourceManager.GetString("PropertyClaimFaqsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Claim FAQs.
        /// </summary>
        internal static string PropertyClaimFaqsTitle {
            get {
                return ResourceManager.GetString("PropertyClaimFaqsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For questions on existing claims, call 844-878-2567.
        ///
        ///If you have documents you’d like to submit on an existing claim, please email the information to claimdocuments@velocityrisk.com. Be sure to include the entire claim number in the subject line and provide any additional details about the claim in the body of the email..
        /// </summary>
        internal static string QuestionsExistingContent {
            get {
                return ResourceManager.GetString("QuestionsExistingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions on an existing claim?.
        /// </summary>
        internal static string QuestionsExistingTitle {
            get {
                return ResourceManager.GetString("QuestionsExistingTitle", resourceCulture);
            }
        }
    }
}
